spring:
  datasource:
    username: root
    password: Qiong2729
    url: jdbc:mysql://localhost:3306/errandsdb?serverTimezone=UTC&useSSL=false&useUniCode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

app:
  uploaded-folder: D:\IntelliJ IDEA\Code\springboot\header
  base-url: file:D:\IntelliJ IDEA\Code\springboot\header\