spring:
  profiles:
    active: dev
  application:
    name: springboot
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

mybatis:
  type-aliases-package: com.lao.pojo
  mapper-locations: classpath:Mybatis/Mapper/*.xml
